[book]
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
language = "en"
multilingual = false
src = "src"
title = "Emergent AI - Smart agents and events for games"

[output.html]
default-theme = "ayu"
